blueprints/basic/views.py
from app import app, db
from imports import *
from flask import session
import random

# -- BLUEPRINT('NAME OF BLUEPRINT, NAME OF APPLICATION, FOLDER CONTAINING LOGIC) -- #
basic_bp = Blueprint('basic_bp', __name__, template_folder='templates')


@basic_bp.route('/')
def home():
    active_page = 'home'
    session["url"] = active_page

    return render_template('index.html', active_page=active_page)
@basic_bp.route('/privacy')
def privacy():
    active_page = 'privacy'
    session["url"] = active_page

    return render_template('privacy.html')


@basic_bp.route('/disclaimer')
def disclaimer():
    active_page = 'disclaimer'
    session["url"] = active_page

    return render_template('disclaimer.html')


@basic_bp.route('/contact')
def contact():
    active_page = 'contact'
    session["url"] = active_page

    active_page = 'contact'
    return render_template('contact.html', active_page=active_page)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="shortcut icon" href="../static/img/favicon.png" type="image/x-icon">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link  rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
  <link  rel="stylesheet" href="{{ url_for('static', filename='css/breadcrumb.css') }}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <meta charset="utf-8">
  <title>Hotel Calm River</title>
</head>
<body>
  <nav class="navbar navbar-expand-md">
    <div class="container-fluid">
      <!-- button when navbar is collapsed-->
      <button class="navbar-toggler me-auto ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- --------------------------------->
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link text-white {% if active_page == 'home' %}bg-success{% endif %}" href="{{ url_for('basic_bp.home') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white {% if active_page == 'rooms' %}bg-success{% endif %}" href="{{ url_for('rooms_bp.index') }}">Kamers</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link text-white {% if active_page == 'contact' %}bg-success{% endif %}" href="{{ url_for('basic_bp.contact') }}">Contact en ligging</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white {% if active_page == 'reviews' %}bg-success{% endif %}" href="{{ url_for('reviews_bp.reviews') }}">Gastenboek</a>
          </li>
          <li class="nav-item dropdown {% if active_page == 'my_calm_river' %}bg-success{% endif %}">
            <a class="nav-link dropdown-toggle text-white" role="button" data-bs-toggle="dropdown">Mijn Calm River</a>
            <ul class="dropdown-menu">
            {% if current_user.is_authenticated %}
              <li><a class="dropdown-item" href="{{ url_for('bookings_bp.booking_index') }}">Boekingen</a></li>
              <li><a class="dropdown-item" href="{{ url_for('profile_bp.profile_index') }}">Profiel</a></li>
              <li><a class="dropdown-item" href="{{ url_for('auth_bp.logout') }}">Uitloggen</a></li>
              <form id="form-logout" action="logout" method="POST" style="display: none;"></form>
            {% else %}
              <li><a class="dropdown-item" href="{{ url_for('auth_bp.login') }}">Inloggen</a></li>
              <li><a class="dropdown-item" href="{{ url_for('auth_bp.register') }}">Registreren</a></li>
            {% endif %}
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <header>
<img src="/static/img/banner.jpg" alt="banner">
  </header>
  <main class="container-fluid">
    {% block content %}

    {% endblock %}
  </main>
  <footer class="p-4 text-center text-white">
    <p>©2023 Calm River Hotels Company</p>
    <span><a href="{{ url_for('basic_bp.privacy') }}">Privacy</a></span>
    <span><a href="{{ url_for('basic_bp.disclaimer') }}">Disclaimer</a></span>
    <span><a href="{{ url_for('basic_bp.contact') }}">Contact</a></span>
  </footer>
</body>
</html>